"""Reproducible NASim topology generation.

The research goal is attack-path discovery on *random* topologies, so topologies
are generated rather than hand-written. Generation is seeded, so "random" and
"reproducible" are not in tension: a topology is fully recoverable from its
config plus its seed, and the config hash proves two runs used the same one.

A frozen seed therefore also satisfies the "one fixed topology" deliverable --
it is one specific, versioned, reproducible instance of this generator.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_TOPOLOGY_CONFIG = REPO_ROOT / "configs" / "topology.yaml"


@dataclass(frozen=True)
class TopologyConfig:
    """Parameters handed to ``nasim.generate``.

    ``num_exploits`` deliberately exceeds ``num_services``. With one exploit per
    service, most hosts admit exactly one applicable exploit and the agent never
    chooses between severities -- the CVE weighting would then be a constant,
    and constants cannot steer a policy. At 8 exploits over 5 services roughly
    90% of hosts offer a real choice (measured over seeds 42-51).
    """

    num_hosts: int = 8
    num_services: int = 5
    num_os: int = 2
    num_processes: int = 3
    num_exploits: int = 8
    num_privescs: int = 3

    # Matches the locked crown-jewel reward of +100.
    r_sensitive: float = 100.0
    r_user: float = 100.0

    exploit_cost: int = 3
    privesc_cost: int = 2
    service_scan_cost: int = 1
    os_scan_cost: int = 1
    subnet_scan_cost: int = 1
    process_scan_cost: int = 1

    # "mixed" gives exploits varied success probabilities, so cost/benefit is
    # not identical across them.
    exploit_probs: str | float = "mixed"
    privesc_probs: str | float = "mixed"

    restrictiveness: int = 5
    step_limit: int = 1000

    @classmethod
    def from_yaml(cls, path: Path = DEFAULT_TOPOLOGY_CONFIG) -> TopologyConfig:
        return cls(**yaml.safe_load(Path(path).read_text())["topology"])

    def config_hash(self) -> str:
        """Stable digest of the generation parameters (seed excluded).

        Two runs sharing this hash were generated by the same rules; combined
        with the seed it pins the exact topology. Logged with every experiment
        so the ablation can prove both arms used identical topologies.
        """
        canonical = json.dumps(asdict(self), sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode()).hexdigest()[:16]


def make_env(config: TopologyConfig | None = None, *, topology_seed: int, **kwargs):
    """Build a NASim environment for one seeded topology.

    Imported lazily so that the reward core, catalogue and their tests remain
    runnable without nasim installed.
    """
    import nasim  # noqa: PLC0415

    config = config or TopologyConfig()
    return nasim.generate(
        num_hosts=config.num_hosts,
        num_services=config.num_services,
        num_os=config.num_os,
        num_processes=config.num_processes,
        num_exploits=config.num_exploits,
        num_privescs=config.num_privescs,
        r_sensitive=config.r_sensitive,
        r_user=config.r_user,
        exploit_cost=config.exploit_cost,
        privesc_cost=config.privesc_cost,
        service_scan_cost=config.service_scan_cost,
        os_scan_cost=config.os_scan_cost,
        subnet_scan_cost=config.subnet_scan_cost,
        process_scan_cost=config.process_scan_cost,
        exploit_probs=config.exploit_probs,
        privesc_probs=config.privesc_probs,
        restrictiveness=config.restrictiveness,
        step_limit=config.step_limit,
        seed=topology_seed,
        name=f"rlredteam-t{topology_seed}",
        **kwargs,
    )


def describe(env) -> dict:
    """Summary of a generated topology, for logging and the rollout script."""
    scenario = env.scenario
    choice_counts = []
    for host in scenario.hosts.values():
        applicable = [
            name
            for name, exploit in scenario.exploits.items()
            if exploit["service"] in host.services
            and (exploit["os"] is None or exploit["os"] == host.os)
        ]
        choice_counts.append(len(applicable))

    return {
        "name": scenario.name,
        "num_hosts": len(scenario.hosts),
        "num_subnets": len(scenario.subnets),
        "services": list(scenario.services),
        "os": list(scenario.os),
        "processes": list(scenario.processes),
        "exploits": list(scenario.exploits),
        "privescs": list(scenario.privescs),
        "sensitive_hosts": {str(k): v for k, v in scenario.sensitive_hosts.items()},
        "step_limit": scenario.step_limit,
        "observation_space": list(env.observation_space.shape),
        "action_space_n": int(env.action_space.n),
        "mean_applicable_exploits_per_host": (
            sum(choice_counts) / len(choice_counts) if choice_counts else 0.0
        ),
        "hosts_with_exploit_choice": sum(1 for c in choice_counts if c > 1),
    }
